#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${POSTGRES_PLANKA_DB};
	CREATE USER ${POSTGRES_PLANKA_USER} WITH PASSWORD '${POSTGRES_PLANKA_PW}';
	ALTER DATABASE ${POSTGRES_PLANKA_DB} OWNER TO ${POSTGRES_PLANKA_USER};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_PLANKA_DB} TO ${POSTGRES_PLANKA_USER};
EOSQL
