#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE ${SERVICE_DB};
	CREATE USER ${SERVICE_USER} WITH PASSWORD '${SERVICE_PW}';
	ALTER DATABASE ${SERVICE_DB} OWNER TO ${SERVICE_USER};
	GRANT ALL PRIVILEGES ON DATABASE ${SERVICE_DB} TO ${SERVICE_USER};
EOSQL
